### ISSUE TITLE
Create mysql user as required by the exporter, per official documentation

### ISSUE THREAD

**Issue by life5ign** [cloudalchemy/ansible-mysqld_exporter#46]
**What is missing?**
Great role, thanks; Creating the mysql user `'exporter@'localhost'` is missing, or saying that the role doesn't create it, at least.  Does it work simply running it as root?
Per docs https://grafana.com/oss/prometheus/exporters/mysql-exporter/?tab=installation

**Why do we need it?**
Currently, the user has to do manual setup to create the `'exporter@'localhost'` user; if he has hundreds of servers, this is prohibitive.
**Environment**

* Role version: 1.0.0

* Ansible version information:

`ansible [core 2.14.1]`

**Anything else we need to know?**:

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
